// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJuPyB7W3IlBI9vMVbuMXUjDzadnd7vE',
    appId: '1:845353893864:web:45c36ea81e062148b3ee5d',
    messagingSenderId: '845353893864',
    projectId: 'fir-a2a17',
    authDomain: 'fir-a2a17.firebaseapp.com',
    storageBucket: 'fir-a2a17.appspot.com',
    measurementId: 'G-T55JNL17TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymuVoVDbl6SKKpdqzVTq251hWwSN-Y6E',
    appId: '1:845353893864:android:8013c726315d6888b3ee5d',
    messagingSenderId: '845353893864',
    projectId: 'fir-a2a17',
    storageBucket: 'fir-a2a17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHAhJ8QZe0CbCeeiJqW4ujZEyT11-j4yQ',
    appId: '1:845353893864:ios:3f841f6f7e6f56ebb3ee5d',
    messagingSenderId: '845353893864',
    projectId: 'fir-a2a17',
    storageBucket: 'fir-a2a17.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHAhJ8QZe0CbCeeiJqW4ujZEyT11-j4yQ',
    appId: '1:845353893864:ios:22c96a5526abc960b3ee5d',
    messagingSenderId: '845353893864',
    projectId: 'fir-a2a17',
    storageBucket: 'fir-a2a17.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
